# Generated by Django 4.1.6 on 2023-02-24 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="restaurants",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="category",
            field=models.ManyToManyField(
                related_name="menuitemcategory", to="restaurants.menucategory"
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="ingredient",
            field=models.ManyToManyField(
                related_name="menuitemingredients", to="restaurants.ingredient"
            ),
        ),
        migrations.AddField(
            model_name="menucategory",
            name="menu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menucategory",
                to="restaurants.menu",
            ),
        ),
        migrations.AddField(
            model_name="menu",
            name="restaurant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="restaurantmenu",
                to="restaurants.restaurant",
            ),
        ),
    ]
