FROM python:3.10-slim-buster
ENV PYTHONUNBUFFERED=1

WORKDIR /allergie

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . .

CMD [ "celery", "-A", "allergie", "worker", "-l", "info" ]